:- module(compat_framework, [
    generate_scryer_out_file/2,
    run_compat_tests_from_file/2,
    default_scryer_out_path/2,
    assert_scryer_crowlog_compat/2,
    assert_scryer_crowlog_compat/3,
    run_compat_test/2,
    chars_contains/2,
    chars_contains_all/2
]).

/** <module> Scryer Compatibility Testing Framework

Provides predicates to:
1. Execute queries natively in Scryer Prolog and produce real output files (.scryer_out).
2. Execute queries in Crowlog and assert full compatibility against the generated Scryer output.
*/

:- use_module(library(charsio)).
:- use_module(library(format)).
:- use_module(library(lambda)).
:- use_module(library(lists)).
:- use_module(library(reif)).
:- use_module(library(si)).
:- use_module('../../src/prolog_lexer').
:- use_module('../../src/prolog_operator_table').
:- use_module('../../src/prolog_reactive_parser').
:- use_module('../../crowlog/crowlog').
:- use_module('../../crowlog/crowlog_toplevel').

%% default_scryer_out_path(+Module, -Path)
default_scryer_out_path(Module, Path) :-
    phrase(format_("build/scryer_compatibility/~a.scryer_out", [Module]), Path).

%% generate_scryer_out_file(:TestCasePred, +OutFilePath)
%  Runs all test cases natively under Scryer Prolog and records the real
%  Scryer output to OutFilePath.
generate_scryer_out_file(Module:TestCasePred, OutFilePath) :-
    atom_or_chars_to_atom(OutFilePath, OutFileAtom),
    open(OutFileAtom, write, Stream),
    format(Stream, "% Scryer Prolog Generated Compatibility Output~n", []),
    format(Stream, "% Automatically generated by Scryer Prolog.~n~n", []),
    findall(ID, call(Module:TestCasePred, ID, _, _, _), IDs),
    generate_cases_to_stream(IDs, Module, TestCasePred, Stream),
    close(Stream).

generate_cases_to_stream([], _, _, _).
generate_cases_to_stream([ID|Rest], Module, TestCasePred, Stream) :-
    call(Module:TestCasePred, ID, _Desc, _KB, Queries),
    eval_queries_in_scryer(Queries, Module, OutputLines),
    format(Stream, "scryer_compat_out(~w, ", [ID]),
    write_string_list_term(Stream, OutputLines),
    format(Stream, ").~n", []),
    generate_cases_to_stream(Rest, Module, TestCasePred, Stream).

write_string_list_term(Stream, Lines) :-
    put_char(Stream, '['),
    write_string_list_items(Lines, Stream),
    put_char(Stream, ']').

write_string_list_items([], _).
write_string_list_items([L|Ls], Stream) :-
    write_escaped_string(Stream, L),
    (   Ls == [] -> true
    ;   format(Stream, ", ", []),
        write_string_list_items(Ls, Stream)
    ).

write_escaped_string(Stream, Chars) :-
    char_code(Quote, 34),
    put_char(Stream, Quote),
    write_escaped_chars(Chars, Stream),
    put_char(Stream, Quote).

write_escaped_chars([], _).
write_escaped_chars([C|Cs], Stream) :-
    char_code(C, Code),
    char_code(BS, 92),
    char_code(Quote, 34),
    if_(Code = 34,
        ( put_char(Stream, BS), put_char(Stream, Quote) ),
        if_(Code = 92,
            ( put_char(Stream, BS), put_char(Stream, BS) ),
            if_(Code = 10,
                ( put_char(Stream, BS), put_char(Stream, 'n') ),
                if_(Code = 9,
                    ( put_char(Stream, BS), put_char(Stream, 't') ),
                    put_char(Stream, C)
                )
            )
        )
    ),
    write_escaped_chars(Cs, Stream).

eval_queries_in_scryer([], _, []).
eval_queries_in_scryer([Q|Qs], Module, AllLines) :-
    eval_single_scryer_query(Q, Module, Lines),
    eval_queries_in_scryer(Qs, Module, RestLines),
    append(Lines, RestLines, AllLines).

eval_single_scryer_query(QueryChars, Module, OutLines) :-
    read_term_from_chars(QueryChars, Goal, [variable_names(VarNames)]),
    (   catch(call(Module:Goal), Error, Status = error(Error)) ->
        (   var(Status) ->
            (   VarNames == [] ->
                OutLines = ["true."]
            ;   filter_scryer_bindings(VarNames, VarNames, OutLines0),
                (   OutLines0 == [] ->
                    OutLines = ["true."]
                ;   OutLines = OutLines0
                )
            )
        ;   phrase(format_("error: ~w", [Error]), ErrLine),
            OutLines = [ErrLine]
        )
    ;   OutLines = ["false."]
    ).

filter_scryer_bindings([], _, []).
filter_scryer_bindings([Name=Val|Rest], AllVars, Out) :-
    (   nonvar(Val) ->
        write_term_to_chars(Val, [quoted(true), variable_names(AllVars)], ValChars),
        phrase(format_("~a = ~s", [Name, ValChars]), Line),
        Out = [Line|RestLines],
        filter_scryer_bindings(Rest, AllVars, RestLines)
    ;   (   member(OtherName=OtherVal, AllVars),
            OtherName \== Name,
            OtherVal == Val
        ) ->
        write_term_to_chars(Val, [quoted(true), variable_names(AllVars)], ValChars),
        phrase(format_("~a = ~s", [Name, ValChars]), Line),
        Out = [Line|RestLines],
        filter_scryer_bindings(Rest, AllVars, RestLines)
    ;   filter_scryer_bindings(Rest, AllVars, Out)
    ).

%% run_compat_tests_from_file(:TestCasePred, +OutFilePath)
%  Reads the Scryer outputs from OutFilePath and executes the test cases in Crowlog,
%  verifying that Crowlog output matches Scryer's actual output.
run_compat_tests_from_file(Module:TestCasePred, OutFilePath) :-
    read_scryer_out_file(OutFilePath, Results),
    findall(ID, call(Module:TestCasePred, ID, _, _, _), IDs),
    run_cases_against_results(IDs, Module:TestCasePred, Results).

read_scryer_out_file(OutFilePath, Results) :-
    read_file_to_chars(OutFilePath, Chars),
    phrase(prolog_tokens(Tokens), Chars),
    default_operator_table(OpT),
    phrase(prolog_parse_program(OpT, [], Clauses, _), Tokens),
    extract_compat_results(Clauses, Results).

extract_compat_results([], []).
extract_compat_results([clause(scryer_compat_out(ID, Lines), _)|Rest], [scryer_compat_out(ID, Lines)|Results]) :-
    extract_compat_results(Rest, Results).
extract_compat_results([_|Rest], Results) :-
    extract_compat_results(Rest, Results).

read_file_to_chars(FilePath, Chars) :-
    atom_or_chars_to_atom(FilePath, FileAtom),
    open(FileAtom, read, Stream),
    read_stream_chars(Stream, Chars),
    close(Stream).

read_stream_chars(Stream, Chars) :-
    get_char(Stream, C),
    if_(C = end_of_file,
        Chars = [],
        ( Chars = [C|Rest],
          read_stream_chars(Stream, Rest)
        )
    ).

atom_or_chars_to_atom(Arg, Atom) :-
    (   atom_si(Arg) ->
        Atom = Arg
    ;   atom_chars(Atom, Arg)
    ).

run_cases_against_results([], _, _).
run_cases_against_results([ID|Rest], Module:TestCasePred, Results) :-
    call(Module:TestCasePred, ID, Desc, KBText, Queries),
    (   member(scryer_compat_out(ID, ExpectedLines), Results) ->
        run_compat_test(Desc, assert_crowlog_matches_lines(KBText, Queries, ExpectedLines))
    ;   format("Missing Scryer reference output for test ~w in ~w~n", [ID, Module]),
        halt(1)
    ),
    run_cases_against_results(Rest, Module:TestCasePred, Results).

assert_crowlog_matches_lines(KBText, Queries, ExpectedLines) :-
    initial_toplevel_state(State0),
    if_(KBText = "",
        State1 = State0,
        ( phrase(prolog_tokens(Tokens), KBText),
          State0 = state(kb(KB0), ops(OpT0), opts(Opts)),
          phrase(prolog_parse_program(OpT0, [expand_mode(pure_dcg)], RawClauses, OpT1), Tokens),
          process_consulted_clauses(RawClauses, state(kb(KB0), ops(OpT1), opts(Opts)), State1, _)
        )
    ),
    append_queries_with_halt(Queries, FullInput),
    crowlog_toplevel_string(FullInput, State1, Output, _),
    (   chars_contains_all(Output, ExpectedLines) ->
        true
    ;   format("Compatibility Mismatch!~nQueries: ~q~nCrowlog Output:~n~s~nExpected Lines from Scryer:~n~q~n",
               [Queries, Output, ExpectedLines]),
        flush_output,
        fail
    ).

append_queries_with_halt([], "halt.\n").
append_queries_with_halt([Q|Qs], Out) :-
    append(Q, "\n", QN),
    append_queries_with_halt(Qs, Rest),
    append(QN, Rest, Out).

%% chars_contains(+Chars, +Sub)
chars_contains(Chars, Sub) :-
    append(_, Rest, Chars),
    append(Sub, _, Rest).

%% chars_contains_all(+Chars, +SubList)
chars_contains_all(_, []).
chars_contains_all(Chars, [Sub|Subs]) :-
    chars_contains(Chars, Sub),
    chars_contains_all(Chars, Subs).

%% assert_scryer_crowlog_compat(+QueryStr, +ExpectedSubstrings)
assert_scryer_crowlog_compat(QueryStr, ExpectedSubstrings) :-
    assert_scryer_crowlog_compat(QueryStr, "", ExpectedSubstrings).

%% assert_scryer_crowlog_compat(+QueryStr, +InitialKBText, +ExpectedSubstrings)
assert_scryer_crowlog_compat(QueryStr, InitialKBText, ExpectedSubstrings) :-
    assert_crowlog_matches_lines(InitialKBText, [QueryStr], ExpectedSubstrings).

%% run_compat_test(+Name, :Goal)
run_compat_test(Name, Goal) :-
    format("  Testing: ~s ... ", [Name]),
    flush_output,
    (   catch(Goal, E, (format("FAIL (exception: ~w)~n", [E]), flush_output, fail)) ->
        format("OK~n", []),
        flush_output
    ;   format("FAIL~n", []),
        flush_output,
        halt(1)
    ).
